version: '3'
services:
  mysql:
    image: 'mysql:5.7.22'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306:3306'
    expose: ["3306"]
    volumes:
      - ./backend:/docker-entrypoint-initdb.d/:ro
    networks:
      - default
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - '3187:3187'
    environment:
      - USER=root
      - PASSWORD=password
      - DATABASE=mydb
    volumes:
      - /app/node_modules
      - ./backend:/app
    networks:
      - default
  # datadog-agent:
  #   image: 'datadog/agent:latest'
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /proc/:/host/proc/:ro
  #     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  #   env_file:
  #     - ~/sandbox.docker.env
  #   environment:
  #     - DD_APM_ENABLED=false
  #     - DD_APM_NON_LOCAL_TRAFFIC=false
  #     - DD_LOGS_ENABLED=true
  #     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
  #     - DD_AC_EXCLUDE=name:datadog-agent
  #   ports:
  #     - '127.0.0.1:8126:8126/tcp'
  #   networks:
  #     - default
networks:
  default:
    driver: bridge