version: "3"
services:
    dummydog:
        image: zachgw/dummydog:latest
        container_name: dummydog
        ports:
            - "3000:3000"
        restart: on-failure
        tty: true
        stdin_open: true
